# -*- coding: utf-8 -*-
"""FC_cfar10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BYWgkwacFqX_7CSxC0cfPJcocIsPnJE
"""

from keras.datasets import cifar10
from keras.utils import to_categorical
from keras import models,layers
import matplotlib.pyplot as plt

# for fully connected
(x_train,y_train),(x_test,y_test)=cifar10.load_data()
x_train=x_train.reshape(50000,32*32*3).astype('float32')/255.
y_train=to_categorical(y_train)
x_val=x_train[:5000]
y_val=y_train[:5000]
x_train=x_train[5000:]
y_train=y_train[5000:]
x_test=x_test.reshape(10000,32*32*3).astype('float32')/255.
y_test=to_categorical(y_test)
print(x_test.shape,y_test.shape,x_val.shape,y_val.shape,x_train.shape,y_train.shape)

model=models.Sequential()
model.add(layers.Dense(512,activation='relu',input_dim=32*32*3))
model.add(layers.Dense(128,activation='relu'))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])
history=model.fit(x_train,y_train,batch_size=128,epochs=30,verbose=0,validation_data=(x_val,y_val))

plt.plot(history.history['accuracy'],label='train_accuracy')
plt.plot(history.history['val_accuracy'],'r',label='val_accuracy')
plt.xlabel('epoch')
plt.ylabel('accuracy')
plt.legend()
plt.grid()
plt.show()
model.summary()

model.evaluate(x_test,y_test)