# -*- coding: utf-8 -*-
"""FC_fm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zfQt__MlCD2AKgH-ALhK1T2S55YpFqJ
"""

from keras.datasets import fashion_mnist
from keras import models,layers
from keras.utils import to_categorical
import matplotlib.pyplot as plt

(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()
x_train=x_train.reshape(60000,28*28).astype('float32')/255.
y_train=to_categorical(y_train)
x_val=x_train[:10000]
y_val=y_train[:10000]
x_train=x_train[10000:]
y_train=y_train[10000:]
x_test=x_test.reshape(10000,28*28).astype('float32')/255.
y_test=to_categorical(y_test)
print(x_train.shape,'\n',y_train.shape,'\n',x_test.shape,'\n',y_test.shape,'\n',x_val.shape,'\n',y_val.shape)

model=models.Sequential()
model.add(layers.Dense(256,activation='relu',input_dim=28*28))
model.add(layers.Dropout(0.3))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(32,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])
history=model.fit(x_train,y_train,batch_size=128,epochs=40,validation_data=(x_val,y_val),verbose=0)

plt.plot(history.history['accuracy'],label='train_accuracy')
plt.plot(history.history['val_accuracy'],'r',label='validation_accuracy')
plt.xlabel('epochs')
plt.ylabel('accuracy')
plt.legend()
plt.grid()
plt.show()

model.summary()

model.evaluate(x_test,y_test)